// Contract addresses for different networks
export const CONTRACT_ADDRESSES = {
  // Filecoin Calibration Testnet
  314159: {
    POLYVERSE_STOREFRONT: '0x7EF74176B51b13e8753C1Ca5055da870a5EC63f2', // Deploy contract here
    USDC_TOKEN: '0x0000000000000000000000000000000000000000', // Mock USDC for testing
    USDFC_TOKEN: '0x0000000000000000000000000000000000000000', // USDFC token address
  },
  // Filecoin Mainnet
  314: {
    POLYVERSE_STOREFRONT: '0x0000000000000000000000000000000000000000',
    USDC_TOKEN: '0x0000000000000000000000000000000000000000',
    USDFC_TOKEN: '0x0000000000000000000000000000000000000000',
  },
  // Polygon Mumbai (for testing)
  80001: {
    POLYVERSE_STOREFRONT: '0x0000000000000000000000000000000000000000',
    USDC_TOKEN: '0x2791bca1f2de4661ed88a30c99a7a9449aa84174', // Real USDC on Mumbai
    USDFC_TOKEN: '0x0000000000000000000000000000000000000000',
  }
};

// Contract ABI (simplified version - full ABI would be generated by compiler)
export const POLYVERSE_STOREFRONT_ABI = [
  // Read functions
  {
    inputs: [{ name: "_creator", type: "address" }],
    name: "creators",
    outputs: [
      { name: "wallet", type: "address" },
      { name: "handle", type: "string" },
      { name: "name", type: "string" },
      { name: "isVerified", type: "bool" },
      { name: "totalEarnings", type: "uint256" },
      { name: "subscriberCount", type: "uint256" },
      { name: "isActive", type: "bool" },
      { name: "createdAt", type: "uint256" }
    ],
    stateMutability: "view",
    type: "function"
  },
  {
    inputs: [{ name: "_productId", type: "uint256" }],
    name: "products",
    outputs: [
      { name: "id", type: "uint256" },
      { name: "creator", type: "address" },
      { name: "title", type: "string" },
      { name: "description", type: "string" },
      { name: "priceUSD", type: "uint256" },
      { name: "contentHash", type: "string" },
      { name: "productType", type: "string" },
      { name: "isActive", type: "bool" },
      { name: "purchaseCount", type: "uint256" },
      { name: "createdAt", type: "uint256" }
    ],
    stateMutability: "view",
    type: "function"
  },
  {
    inputs: [
      { name: "_user", type: "address" },
      { name: "_productId", type: "uint256" }
    ],
    name: "checkAccess",
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
    type: "function"
  },
  {
    inputs: [{ name: "_handle", type: "string" }],
    name: "getCreatorByHandle",
    outputs: [
      { name: "wallet", type: "address" },
      { name: "handle", type: "string" },
      { name: "name", type: "string" },
      { name: "isVerified", type: "bool" },
      { name: "totalEarnings", type: "uint256" },
      { name: "subscriberCount", type: "uint256" },
      { name: "isActive", type: "bool" },
      { name: "createdAt", type: "uint256" }
    ],
    stateMutability: "view",
    type: "function"
  },
  {
    inputs: [{ name: "_creator", type: "address" }],
    name: "getProductsByCreator",
    outputs: [{ name: "", type: "uint256[]" }],
    stateMutability: "view",
    type: "function"
  },
  // Write functions
  {
    inputs: [
      { name: "_handle", type: "string" },
      { name: "_name", type: "string" }
    ],
    name: "registerCreator",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    inputs: [
      { name: "_title", type: "string" },
      { name: "_description", type: "string" },
      { name: "_priceUSD", type: "uint256" },
      { name: "_contentHash", type: "string" },
      { name: "_productType", type: "string" }
    ],
    name: "createProduct",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    inputs: [
      { name: "_productId", type: "uint256" },
      { name: "_paymentToken", type: "address" }
    ],
    name: "purchaseProduct",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    inputs: [
      { name: "_creator", type: "address" },
      { name: "_amount", type: "uint256" },
      { name: "_paymentToken", type: "address" }
    ],
    name: "sendTip",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function"
  },
  // Events
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "creator", type: "address" },
      { indexed: false, name: "handle", type: "string" },
      { indexed: false, name: "name", type: "string" }
    ],
    name: "CreatorRegistered",
    type: "event"
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "productId", type: "uint256" },
      { indexed: true, name: "creator", type: "address" },
      { indexed: false, name: "title", type: "string" },
      { indexed: false, name: "price", type: "uint256" }
    ],
    name: "ProductCreated",
    type: "event"
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "productId", type: "uint256" },
      { indexed: true, name: "buyer", type: "address" },
      { indexed: true, name: "creator", type: "address" },
      { indexed: false, name: "amount", type: "uint256" }
    ],
    name: "ProductPurchased",
    type: "event"
  }
] as const;

export const ERC20_ABI = [
  {
    inputs: [
      { name: "spender", type: "address" },
      { name: "amount", type: "uint256" }
    ],
    name: "approve",
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    inputs: [
      { name: "owner", type: "address" },
      { name: "spender", type: "address" }
    ],
    name: "allowance",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function"
  },
  {
    inputs: [{ name: "account", type: "address" }],
    name: "balanceOf",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function"
  },
  {
    inputs: [],
    name: "decimals",
    outputs: [{ name: "", type: "uint8" }],
    stateMutability: "view",
    type: "function"
  }
] as const;